### ISSUE TITLE
    drone ds[drones];

### ISSUE THREAD

**Issue by 00xglitch** [Tanjoodo/hashcode#1]
Error of variable length array of non-POD element type

**Comment by Tanjoodo** [comment]
use the c++11 standard

**Comment by 00xglitch** [comment]
> use the c++11 standard

That's your solution !!?

**Comment by Tanjoodo** [comment]
lmao seems reasonable

**Comment by 00xglitch** [comment]
where the heck can i reach you ?

**Comment by Tanjoodo** [comment]
Email? Lol. 

I have WhatsApp and Signal
>
